version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obd_api
    image: obd_api
    env_file:
      - app.env
    ports:
      - "9091:9091"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  app:
    driver: local


networks:
  default:
    external:
      name: postgres_network
