version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obd_api
    ports:
      - "9091:9091"
    environment:
      - DB_SOURCE=postgresql://dev:secret@postgres:5432/mln_obd?sslmode=disable
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
    

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/certificates:/etc/nginx/certificates
  #   depends_on:
  #     - app
volumes:
  app:
    driver: local