DROP TABLE IF EXISTS "areas";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "car_brands";
DROP TABLE IF EXISTS "car_brand_models";
DROP TABLE IF EXISTS "cars";
DROP TABLE IF EXISTS "centers";
DROP TABLE IF EXISTS "reviews";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "codes";
DROP TABLE IF EXISTS "session_codes";
DROP TABLE IF EXISTS "winch";








