// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: obd/v1/session/create_rpc.proto

package obdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLive bool `protobuf:"varint,1,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"` //indicates if session loads live data from car to attach results to session_valyes if its not soit will insert into session codes
}

func (x *SessionCreateRequest) Reset() {
	*x = SessionCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateRequest) ProtoMessage() {}

func (x *SessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateRequest.ProtoReflect.Descriptor instead.
func (*SessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SessionCreateRequest) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

type SessionCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int32 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionCreateResponse) Reset() {
	*x = SessionCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateResponse) ProtoMessage() {}

func (x *SessionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateResponse.ProtoReflect.Descriptor instead.
func (*SessionCreateResponse) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SessionCreateResponse) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// attach codes
type SessionAttachCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Codes     string `protobuf:"bytes,2,opt,name=codes,proto3" json:"codes,omitempty"`
}

func (x *SessionAttachCodesRequest) Reset() {
	*x = SessionAttachCodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAttachCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAttachCodesRequest) ProtoMessage() {}

func (x *SessionAttachCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAttachCodesRequest.ProtoReflect.Descriptor instead.
func (*SessionAttachCodesRequest) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *SessionAttachCodesRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionAttachCodesRequest) GetCodes() string {
	if x != nil {
		return x.Codes
	}
	return ""
}

type SessionAttachCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *SessionAttachCodesResponse) Reset() {
	*x = SessionAttachCodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAttachCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAttachCodesResponse) ProtoMessage() {}

func (x *SessionAttachCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAttachCodesResponse.ProtoReflect.Descriptor instead.
func (*SessionAttachCodesResponse) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *SessionAttachCodesResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// attach values
type SessionVaue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueKey  string `protobuf:"bytes,2,opt,name=value_key,json=valueKey,proto3" json:"value_key,omitempty"`
	ValueData string `protobuf:"bytes,3,opt,name=value_data,json=valueData,proto3" json:"value_data,omitempty"`
}

func (x *SessionVaue) Reset() {
	*x = SessionVaue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionVaue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionVaue) ProtoMessage() {}

func (x *SessionVaue) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionVaue.ProtoReflect.Descriptor instead.
func (*SessionVaue) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *SessionVaue) GetValueKey() string {
	if x != nil {
		return x.ValueKey
	}
	return ""
}

func (x *SessionVaue) GetValueData() string {
	if x != nil {
		return x.ValueData
	}
	return ""
}

type OBDModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed         string `protobuf:"bytes,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Rpm           string `protobuf:"bytes,2,opt,name=rpm,proto3" json:"rpm,omitempty"`
	AirIntakeTemp string `protobuf:"bytes,3,opt,name=air_intake_temp,json=airIntakeTemp,proto3" json:"air_intake_temp,omitempty"`
	EngineLoad    string `protobuf:"bytes,7,opt,name=engine_load,json=engineLoad,proto3" json:"engine_load,omitempty"`
	ModuleVoltage string `protobuf:"bytes,8,opt,name=module_voltage,json=moduleVoltage,proto3" json:"module_voltage,omitempty"`
}

func (x *OBDModel) Reset() {
	*x = OBDModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OBDModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OBDModel) ProtoMessage() {}

func (x *OBDModel) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OBDModel.ProtoReflect.Descriptor instead.
func (*OBDModel) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *OBDModel) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *OBDModel) GetRpm() string {
	if x != nil {
		return x.Rpm
	}
	return ""
}

func (x *OBDModel) GetAirIntakeTemp() string {
	if x != nil {
		return x.AirIntakeTemp
	}
	return ""
}

func (x *OBDModel) GetEngineLoad() string {
	if x != nil {
		return x.EngineLoad
	}
	return ""
}

func (x *OBDModel) GetModuleVoltage() string {
	if x != nil {
		return x.ModuleVoltage
	}
	return ""
}

// attach values
type SessionAttachValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64     `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ObdModel  *OBDModel `protobuf:"bytes,2,opt,name=obd_model,json=obdModel,proto3" json:"obd_model,omitempty"`
}

func (x *SessionAttachValuesRequest) Reset() {
	*x = SessionAttachValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAttachValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAttachValuesRequest) ProtoMessage() {}

func (x *SessionAttachValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAttachValuesRequest.ProtoReflect.Descriptor instead.
func (*SessionAttachValuesRequest) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *SessionAttachValuesRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionAttachValuesRequest) GetObdModel() *OBDModel {
	if x != nil {
		return x.ObdModel
	}
	return nil
}

type SessionAttachValuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *SessionAttachValuesResponse) Reset() {
	*x = SessionAttachValuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_create_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAttachValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAttachValuesResponse) ProtoMessage() {}

func (x *SessionAttachValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_create_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAttachValuesResponse.ProtoReflect.Descriptor instead.
func (*SessionAttachValuesResponse) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_create_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *SessionAttachValuesResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_obd_v1_session_create_rpc_proto protoreflect.FileDescriptor

var file_obd_v1_session_create_rpc_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x62, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x6f, 0x62, 0x64, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x50, 0x0a, 0x19, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x36, 0x0a, 0x1a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x0b, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x22, 0xa2, 0x01, 0x0a, 0x08, 0x4f, 0x42, 0x44, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x70, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x70, 0x6d, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x69, 0x72,
	0x5f, 0x69, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x54, 0x65, 0x6d,
	0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x4c, 0x6f,
	0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x76, 0x6f, 0x6c,
	0x74, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x22, 0x6a, 0x0a, 0x1a, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x6f, 0x62, 0x64, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x62, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x42, 0x44, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x6f, 0x62, 0x64,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x37, 0x0a, 0x1b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x90,
	0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x72, 0x77,
	0x69, 0x73, 0x68, 0x64, 0x65, 0x76, 0x2f, 0x6f, 0x62, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x62, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x6f, 0x62, 0x64, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58,
	0xaa, 0x02, 0x06, 0x4f, 0x62, 0x64, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x4f, 0x62, 0x64, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x12, 0x4f, 0x62, 0x64, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x4f, 0x62, 0x64, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_obd_v1_session_create_rpc_proto_rawDescOnce sync.Once
	file_obd_v1_session_create_rpc_proto_rawDescData = file_obd_v1_session_create_rpc_proto_rawDesc
)

func file_obd_v1_session_create_rpc_proto_rawDescGZIP() []byte {
	file_obd_v1_session_create_rpc_proto_rawDescOnce.Do(func() {
		file_obd_v1_session_create_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_obd_v1_session_create_rpc_proto_rawDescData)
	})
	return file_obd_v1_session_create_rpc_proto_rawDescData
}

var file_obd_v1_session_create_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_obd_v1_session_create_rpc_proto_goTypes = []interface{}{
	(*SessionCreateRequest)(nil),        // 0: obd.v1.SessionCreateRequest
	(*SessionCreateResponse)(nil),       // 1: obd.v1.SessionCreateResponse
	(*SessionAttachCodesRequest)(nil),   // 2: obd.v1.SessionAttachCodesRequest
	(*SessionAttachCodesResponse)(nil),  // 3: obd.v1.SessionAttachCodesResponse
	(*SessionVaue)(nil),                 // 4: obd.v1.SessionVaue
	(*OBDModel)(nil),                    // 5: obd.v1.OBDModel
	(*SessionAttachValuesRequest)(nil),  // 6: obd.v1.SessionAttachValuesRequest
	(*SessionAttachValuesResponse)(nil), // 7: obd.v1.SessionAttachValuesResponse
}
var file_obd_v1_session_create_rpc_proto_depIdxs = []int32{
	5, // 0: obd.v1.SessionAttachValuesRequest.obd_model:type_name -> obd.v1.OBDModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_obd_v1_session_create_rpc_proto_init() }
func file_obd_v1_session_create_rpc_proto_init() {
	if File_obd_v1_session_create_rpc_proto != nil {
		return
	}
	file_obd_v1_session_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_obd_v1_session_create_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAttachCodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAttachCodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionVaue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OBDModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAttachValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_create_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAttachValuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_obd_v1_session_create_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obd_v1_session_create_rpc_proto_goTypes,
		DependencyIndexes: file_obd_v1_session_create_rpc_proto_depIdxs,
		MessageInfos:      file_obd_v1_session_create_rpc_proto_msgTypes,
	}.Build()
	File_obd_v1_session_create_rpc_proto = out.File
	file_obd_v1_session_create_rpc_proto_rawDesc = nil
	file_obd_v1_session_create_rpc_proto_goTypes = nil
	file_obd_v1_session_create_rpc_proto_depIdxs = nil
}
