// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: obd/v1/session/list_rpc.proto

package obdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionsListRequest) Reset() {
	*x = SessionsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_list_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsListRequest) ProtoMessage() {}

func (x *SessionsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_list_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsListRequest.ProtoReflect.Descriptor instead.
func (*SessionsListRequest) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_list_rpc_proto_rawDescGZIP(), []int{0}
}

type SessionsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sessions []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
}

func (x *SessionsListResponse) Reset() {
	*x = SessionsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_list_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsListResponse) ProtoMessage() {}

func (x *SessionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_list_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsListResponse.ProtoReflect.Descriptor instead.
func (*SessionsListResponse) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_list_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SessionsListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionGetCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionGetCodesRequest) Reset() {
	*x = SessionGetCodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_list_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionGetCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetCodesRequest) ProtoMessage() {}

func (x *SessionGetCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_list_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetCodesRequest.ProtoReflect.Descriptor instead.
func (*SessionGetCodesRequest) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_list_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *SessionGetCodesRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type SessionGetCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []*Code `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *SessionGetCodesResponse) Reset() {
	*x = SessionGetCodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obd_v1_session_list_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionGetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetCodesResponse) ProtoMessage() {}

func (x *SessionGetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_v1_session_list_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetCodesResponse.ProtoReflect.Descriptor instead.
func (*SessionGetCodesResponse) Descriptor() ([]byte, []int) {
	return file_obd_v1_session_list_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *SessionGetCodesResponse) GetCodes() []*Code {
	if x != nil {
		return x.Codes
	}
	return nil
}

var File_obd_v1_session_list_rpc_proto protoreflect.FileDescriptor

var file_obd_v1_session_list_rpc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x62, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x6f, 0x62, 0x64, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x14, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x37, 0x0a, 0x16, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x17, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x8e, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x2e, 0x6f, 0x62, 0x64, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x70, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x72, 0x77, 0x69, 0x73, 0x68, 0x64, 0x65, 0x76, 0x2f, 0x6f,
	0x62, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x62,
	0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x3b, 0x6f, 0x62, 0x64,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x4f, 0x62, 0x64, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x06, 0x4f, 0x62, 0x64, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x12, 0x4f, 0x62, 0x64,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x07, 0x4f, 0x62, 0x64, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_obd_v1_session_list_rpc_proto_rawDescOnce sync.Once
	file_obd_v1_session_list_rpc_proto_rawDescData = file_obd_v1_session_list_rpc_proto_rawDesc
)

func file_obd_v1_session_list_rpc_proto_rawDescGZIP() []byte {
	file_obd_v1_session_list_rpc_proto_rawDescOnce.Do(func() {
		file_obd_v1_session_list_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_obd_v1_session_list_rpc_proto_rawDescData)
	})
	return file_obd_v1_session_list_rpc_proto_rawDescData
}

var file_obd_v1_session_list_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_obd_v1_session_list_rpc_proto_goTypes = []interface{}{
	(*SessionsListRequest)(nil),     // 0: obd.v1.SessionsListRequest
	(*SessionsListResponse)(nil),    // 1: obd.v1.SessionsListResponse
	(*SessionGetCodesRequest)(nil),  // 2: obd.v1.SessionGetCodesRequest
	(*SessionGetCodesResponse)(nil), // 3: obd.v1.SessionGetCodesResponse
	(*Session)(nil),                 // 4: obd.v1.Session
	(*Code)(nil),                    // 5: obd.v1.Code
}
var file_obd_v1_session_list_rpc_proto_depIdxs = []int32{
	4, // 0: obd.v1.SessionsListResponse.sessions:type_name -> obd.v1.Session
	5, // 1: obd.v1.SessionGetCodesResponse.codes:type_name -> obd.v1.Code
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_obd_v1_session_list_rpc_proto_init() }
func file_obd_v1_session_list_rpc_proto_init() {
	if File_obd_v1_session_list_rpc_proto != nil {
		return
	}
	file_obd_v1_session_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_obd_v1_session_list_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_list_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_list_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionGetCodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obd_v1_session_list_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionGetCodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_obd_v1_session_list_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obd_v1_session_list_rpc_proto_goTypes,
		DependencyIndexes: file_obd_v1_session_list_rpc_proto_depIdxs,
		MessageInfos:      file_obd_v1_session_list_rpc_proto_msgTypes,
	}.Build()
	File_obd_v1_session_list_rpc_proto = out.File
	file_obd_v1_session_list_rpc_proto_rawDesc = nil
	file_obd_v1_session_list_rpc_proto_goTypes = nil
	file_obd_v1_session_list_rpc_proto_depIdxs = nil
}
